src/shared/pager.c

musl marks those variables as readonly and therefore fails while building at this file:
```
CC       src/shared/libshared_la-spawn-polkit-agent.lo
src/shared/pager.c: In function 'pager_close':
src/shared/pager.c:153:16: error: assignment of read-only variable 'stdout'
stdout = safe_fclose(stdout);
^
src/shared/pager.c:154:16: error: assignment of read-only variable 'stderr'
stderr = safe_fclose(stderr);
^
make[2]: *** [Makefile:2814: src/shared/libshared_la-pager.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:3368: all-recursive] Error 1
make: *** [Makefile:1535: all] Error 2
```

fix musl-libc for 227.2/227.3: do not change stderr/stdout variables.

---

src/basic/log.c
src/basic/stdio-util.h

This patch fix the musl libc builds at VoidLinux. Comes from 228.1, but applies to master too.

228.1: fix musl

---

src/basic/fs-util.h

faccessat does not support AT_SYMLINK_NOFOLLOW with musl.

musl-fix for 228.3

---

src/basic/process-util.c
src/shared/musl_missing.h
src/test/test-sizeof.c

- src/shared/musl_missing.h: mostly adaptation to new meson build system and defining __register_atfork to pthread_atfork due to the lack of the former on musl systems.
- src/test/test-sizeof.c has typedefs not available on musl guarded against them.
- src/basic/process-util.c has the definition of __register_atfork guarded to be used only on glibc systems
More info in each commit.

Fixes for musl libc.

---

src/login/elogind.c

While testing for devuan i came accross an issue with daemonizing. Devuan's sysvinit uses "startpar" to implement parallel startup of services. After the system has booted there was still a running instance of "startpar" waiting for elogind, although elogind was already running as service. 
I found that this problem can be solved by explicitly closing stdin/stdout/stderr file descriptors. Not sure if my solution is optimal or correct.

Fix proper daemonizing with sysvinit/startpar

---

meson.build
src/basic/login-util.h
src/login/73-seat-late.rules.in
src/uaccess-command/uaccess-command.c

The uaccess udev builtin command is only used by logind and contains
functionality only implemented in logind. As such, while we cannot
write udev-builtin commands in elogind (not being udev), we can write
standalone binaries and rewrite our udev rules to use them instead.
This fixes the feature of granting users access to devices using a user
ACL which is toggled only when the user is associated with an active
session. Currently this functionality is half broken, as while the ACL
is granted and revoked while VT-switching, it is not granted to new
devices as they are plugged in. This issue is fixed by this commit.

Introduce elogind-uaccess-command to replace udev's uaccess builtin.

---

src/shared/musl_missing.h

Before this fix, elogind did not compile on musl, as the header "musl-missing.h" tries to include a nonexistant header: "config.h". This patch fixes that. Musl compiles with no issues once this patch is administered.

Fix build on musl

---

src/shared/musl_missing.h

i have come again.
This adds missing macros for FTW_* stuff used on src/basic/locale-util.c  src/core/mount-setup.c .
it is untested as i don't own a *-musl system but it compiles on aarch64-musl. 
i still need to run the tests.

musl_missing.h: add FTW_* macros missing for musl libc.

---

meson.build
src/basic/missing.h

Fixes issue #74
Signed-off-by: Christoph Willing <chris.willing@linux.com>

Deal with glibc228

---

src/shared/musl_missing.h

This is the first in a series of patches meant to make elogind compile against musl libc again.

musl_missing.h: add __compar_d_fn_t

---

src/basic/parse-printf-format.c
src/basic/parse-printf-format.h

Meson works by setting 0 for not found and 1 for found, so check against
the value.

printf: check for values of HAVE_PRINTF_H not if defined or not.

---

src/shared/musl_missing.h

Not necessary anymore as all invocations of it are being replaced with
chase_symlink.

musl_missing.h: remove canonicalize_file_name

---

src/basic/cgroup-util.c

The session state is an env file, of which the first line is
```
```
so `read_one_line_file` won't return a value that can be parsed to a UID. Have updated to use `parse_env_file` to correctly read the UID. 
This fix is required due to a change introduced in gnome-session-3.34.2, as detailed here: https://gitlab.gnome.org/GNOME/gnome-session/issues/44

Fix cg_path_get_owner_uid

---

meson.build

musl [added support for reallocarray][0], but the function prototype is
declared in `stdlib.h` instead of `malloc.h`.
Update the check for reallocarray to check both in `malloc.h` and
`stdlib.h`.
[0]:https://git.musl-libc.org/cgit/musl/commit/?id=821083ac7b54eaa040d5a8ddc67c6206a175e0ca

Look for reallocarray in stdlib.h as well

---

src/login/logind.c

When the dbus daemon is killed, elogind does not exit its main loop, so that it is not killed. After a subsequent restart of dbus, the elogind daemon cannot be started, to that the org.freedesktop.login1 name cannot be owned. Setting the exit_on_disconnect flag in the bus struct allows elogind to exit its main loop when dbus is killed.

Patch for issue #224: exit on disconnect

---

src/login/eloginctl.c
src/login/loginctl.c

--quiet was ported from systemctl but only suppresses a single message in loginctl. Also, the short form -q is not recognized because it was never added to getopt_long.
Since this option barely works in the first place, I doubt anyone will miss it.

loginctl: remove useless --quiet option

---

man/loginctl.xml

A couple options are missing from the man page. -c is documented but has a typo. I chose not to add --quiet because of #228.

man/loginctl: document missing options

---

src/basic/cgroup-util.c
src/shared/cgroup-setup.c

systemd is fixed on itself as the cgroup controller, but elogind is only a very rudimentary cgroup controller and relies on third-party controllers like openrc.
This leads to problems on hybrid configurations, because the systemd-code assumes, that a found unified structure is all that is needed. But session assignments might follow the legacy path, not the unified one, so elogind does not find session ids via process PIDs.
This PR makes elogind to also check for a legacy hybrid hierarchy even if the presence of a unified hierarchy is confirmed.
The first step to remedy the situation is to be aware that `/sys/fs/cgroup/<controller>` exists, even if `/sys/fs/cgroup/unified` was found.
The second step is to also check for `1:name=<controller>:/<session id>` entries in `/proc/<PID>/cgroup`, …

Fix controller detect in cgroup session search by PID

---

src/login/logind.c
src/shared/bus-util.c

fix errors from merging, both patches avoid asserts that are immediately hit on running elogind and loginctl. please review.

Migration fixes 254 pre take 1

---

src/basic/musl_missing.h

This re-adds the GNU basename macro when compiling on musl.
Alternatively `#include <libgen.h>` can be added to `musl_missing.h`, this would continue the behavior as it currently is before the following musl change, although code will need to expect POSIX basename instead of GNU basename.
elgoind was able to build without either change on musl due to it containing a declaration in string.h (despite it only providing POSIX basename), this has recently been removed:
https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7
Let me know which way makes the most sense.

musl_missing.h: re-add GNU basename macro for musl

---

meson.build

get_option('libexecdir') is designed to strip the prefix and return a relative directory if the top level directory is the same as what is set by --prefix. Handle this by appropriately joining directories if needed.
There might be other options in there that need handling like this, but this was the main one we encountered in Artix. You get `lib/elogind` otherwise.

meson: fix handling of libexecdir option

---

src/basic/rlimit-util.c

This was incorrect, because RLIM_FMT is not the format specifier for uintmax_t.
Since 53e84063a ("Change RLIM_FMT to '%llu' for non-glibc builds (#269)"), RLIM_FMT is correct for musl, so there's no longer any need for this casting version.

Remove outdated musl hack in rlimit_nofile_safe

---

src/login/10-elogind.conf

This pull request addresses [#300](https://github.com/elogind/elogind/issues/300).
The configuration file 10-elogind.conf includes a misleading comment:
```
```
This reference is incorrect, as the file is related to ```elogind``` configuration, not ```sleep.conf```.
```
-# See sleep.conf(5) for details.
+# See logind.conf(5) for details.
```
This corrects the documentation to point users and developers to the appropriate manual page (logind.conf(5)), improving clarity and usability.

Fix incorrect man page reference from sleep.conf(5) to logind.conf(5)
